= blkpg-part(1)
:doctype: manpage
:author: Gaël PORTAY
:email: gael.portay@gmail.com
:lang: en
:man manual: BlockPG Partition Manual
:man source: blkpg-part 1

== NAME

blkpg-part - partition table and disk geometry handling utility

== SYNOPSIS

*blkpg-part* [OPTIONS] add|resize DEVNAME PNO START LENGTH

*blkpg-part* [OPTIONS] delete DEVNAME PNO

== DESCRIPTION

*blkpg-part(1)* adds, resizes and deletes partitions using the according
_BLKPG_ADD_PARTITION_, _BLKPG_DEL_PARTITION_ or _BLKPG_RESIZE_PARTITION_
*ioctl(3P)*.

_DEVNAME_: partition name, like sda5 or c0d1p2, to be used in kernel messages.

_PNO_: partition number.

_START_: starting offset in bytes.

_LENGTH_: length in bytes.

== OPTIONS

**-l or --volume-name LABEL**::
	Set volume label (Unused at present - linux 4.15).

**-h or --help**::
	Display this message.

**-V or --version**::
	Display the version.

== EXIT STATUS

Exits success if command-line is valid; exits failure otherwise.

== PATCHES

Submit patches at *https://github.com/gportay/blkpg-part/pulls*

== BUGS

Report bugs at *https://github.com/gportay/blkpg-part/issues*

== AUTHOR

Written by Gaël PORTAY *gael.portay@gmail.com*

== COPYRIGHT

Copyright 2018,2021 Gaël PORTAY
               2021 Collabora Ltd.
               2018 Savoir-Faire Linux Inc.

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the Free
Software Foundation, either version 2.1 of the License, or (at your option) any
later version.

== SEE ALSO

ioctl(3P)
