= blkpgtab-generator(8)
:doctype: manpage
:author: Gaël PORTAY
:email: gael.portay@gmail.com
:lang: en
:man manual: Unit generator for /etc/blkpgtab
:man source: blkpgtab-generator 1

== NAME

blkpgtab-generator - Unit generator for /etc/blkpgtab

== SYNOPSIS

/usr/lib/systemd/system-generators/blkpgtab-generator

== DESCRIPTION

blkpgtab-generator is a generator that translates /etc/blkpgtab (see
**blkpgtab**(5) for details) into native systemd units early at boot and when
configuration of the system manager is reloaded. This will instantiate service
units as necessary.

blkpgtab-generator implements **systemd.generator**(7).

== KERNEL COMMAND LINE

blkpgtab-generator understands the following kernel command line parameters:

__blkpgtab=__::
Takes a boolean argument. Defaults to "yes". If "no", causes the generator to
ignore any mounts or swap devices configured in /etc/blkpgtab.

== PATCHES

Submit patches at *https://github.com/gportay/blkpg-part/pulls*

== BUGS

Report bugs at *https://github.com/gportay/blkpg-part/issues*

== AUTHOR

Written by Gaël PORTAY *gael.portay@gmail.com*

== COPYRIGHT

Copyright 2023-2024 Gaël PORTAY
          2023-2024 Rtone.

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the Free
Software Foundation, either version 2.1 of the License, or (at your option) any
later version.

== SEE ALSO

**systemd**(1), **blkpgtab**(5)
